FROM rapidsai/rapidsai:0.10-cuda10.1-runtime-ubuntu18.04

ENV CONDA_ENV rapids

RUN source activate $CONDA_ENV && \
    apt-get update && \
    apt-get install -y screen unzip git vim htop font-manager && \
    rm -rf /var/lib/apt/*

RUN source activate $CONDA_ENV && jupyter labextension install @jupyter-widgets/jupyterlab-manager

RUN source activate $CONDA_ENV && conda install -y -c conda-forge ipyvolume && conda clean -yac *
RUN source activate $CONDA_ENV && jupyter labextension install ipyvolume

RUN source activate $CONDA_ENV && conda install -c conda-forge python-graphviz && conda clean -yac *

# there is a PR in dask_kubernetes that adds a lot of new functionality, we are installing directly from there for now
#RUN source activate $CONDA_ENV && pip install git+https://github.com/dask/dask-kubernetes.git
#RUN source activate $CONDA_ENV && pip install git+https://github.com/dask/distributed.git@master
#RUN source activate $CONDA_ENV && pip install git+https://github.com/jacobtomlinson/dask-kubernetes.git@spec-cluster

RUN source activate $CONDA_ENV && mkdir /rapids-dask-hpo && cd /rapids-dask-hpo && git clone https://github.com/miroenev/rapids	

RUN source activate $CONDA_ENV && mkdir /k8s-rapids-dask && cd /k8s-rapids-dask && git clone --depth=1 https://github.com/supertetelman/k8s-rapids-dask

EXPOSE 8888
EXPOSE 8787

WORKDIR /
